# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'JMCiBeaconManager_Example' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JMCiBeaconManager_Example
  
  pod 'JMCiBeaconManager', :git => 'https://github.com/appzzman/JMCBeaconManager.git', :tag => '0.1.6'

end
